// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


 

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB20FCqhU5W4eeIqsIhcIpA8o9ueakZUU8',
    appId: '1:74436960262:web:86f3673cc3c1a073b9e387',
    messagingSenderId: '74436960262',
    projectId: 'hsklportal',
    authDomain: 'hsklportal.firebaseapp.com',
    storageBucket: 'hsklportal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9SQ1OKJl1AiCh_lnGBCUQNQ0cIGnDYWg',
    appId: '1:74436960262:android:357be5fcb86da18db9e387',
    messagingSenderId: '74436960262',
    projectId: 'hsklportal',
    storageBucket: 'hsklportal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeYZ7ERZ65c7XodXAlg60ln4xtqmROqyQ',
    appId: '1:74436960262:ios:ddea4a2eb5b9c982b9e387',
    messagingSenderId: '74436960262',
    projectId: 'hsklportal',
    storageBucket: 'hsklportal.appspot.com',
    iosClientId: '74436960262-r69meoqtkq9laiul2umu0tl92915m8b7.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
